import "./_styles/index.scss";

export const metadata = {
  title: "Bio ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="it">
      <body className="">{children}</body>
    </html>
  );
}
